language: ruby
sudo: required
rvm:
 - 2.2.2

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/ecb6a1c68cfb7a8924d6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
